// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ordis.Migrations
{
    [DbContext(typeof(OrdisContext))]
    [Migration("20260131165502_FleshOutItemsAndSpells")]
    partial class FleshOutItemsAndSpells
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultRollDie")
                        .HasColumnType("text");

                    b.Property<string>("DungeonMasterId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatModifierFormula")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DungeonMasterId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Gauge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Colour")
                        .HasColumnType("text");

                    b.Property<int>("GaugeType")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("Max")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerCharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCharacterId");

                    b.ToTable("Gauges");
                });

            modelBuilder.Entity("IndividualRollResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "expression");

                    b.Property<float>("Result")
                        .HasColumnType("real")
                        .HasAnnotation("Relational:JsonPropertyName", "result");

                    b.Property<int?>("RollResultId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RollResultId");

                    b.ToTable("PastRolls");

                    b.HasAnnotation("Relational:JsonPropertyName", "rolls");
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlayerCharacterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCharacterId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("PlayerCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<int?>("Mana")
                        .HasColumnType("integer")
                        .HasColumnName("mana");

                    b.Property<string>("ManaReadoutChannelId")
                        .HasColumnType("text")
                        .HasColumnName("mana_readout_channel_id");

                    b.Property<string>("ManaReadoutMessageId")
                        .HasColumnType("text")
                        .HasColumnName("mana_readout_message_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RollServerId")
                        .HasColumnType("text")
                        .HasColumnName("roll_server_id");

                    b.Property<string>("SavedRolls")
                        .HasColumnType("text")
                        .HasColumnName("saved_rolls");

                    b.Property<string>("SpellBlock")
                        .HasColumnType("text")
                        .HasColumnName("spell_block");

                    b.Property<string>("SpellBlockChannelId")
                        .HasColumnType("text")
                        .HasColumnName("spell_block_channel_id");

                    b.Property<string>("SpellBlockHash")
                        .HasColumnType("text")
                        .HasColumnName("spell_block_hash");

                    b.Property<string>("SpellBlockMessageId")
                        .HasColumnType("text")
                        .HasColumnName("spell_block_message_id");

                    b.Property<string>("StatBlockChannelId")
                        .HasColumnType("text")
                        .HasColumnName("stat_block_channel_id");

                    b.Property<string>("StatBlockHash")
                        .HasColumnType("text")
                        .HasColumnName("stat_block_hash");

                    b.Property<string>("StatBlockJson")
                        .HasColumnType("text")
                        .HasColumnName("stat_block");

                    b.Property<string>("StatBlockMessageId")
                        .HasColumnType("text")
                        .HasColumnName("stat_block_message_id");

                    b.Property<string>("StatBlockServerId")
                        .HasColumnType("text")
                        .HasColumnName("stat_block_server_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("new_characters_pkey");

                    b.HasIndex("CampaignId");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("Roll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RollString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SpellId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SpellId");

                    b.ToTable("Roll");
                });

            modelBuilder.Entity("RollResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "message");

                    b.Property<int?>("PlayerCharacterId")
                        .HasColumnType("integer");

                    b.Property<float>("Result")
                        .HasColumnType("real")
                        .HasAnnotation("Relational:JsonPropertyName", "result");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCharacterId");

                    b.ToTable("RollResults");
                });

            modelBuilder.Entity("Server", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DefaultRollChannel")
                        .HasColumnType("text")
                        .HasColumnName("default_roll_channel");

                    b.Property<string>("DefaultRollServer")
                        .HasColumnType("text")
                        .HasColumnName("default_roll_server");

                    b.HasKey("Id")
                        .HasName("servers_pkey");

                    b.ToTable("servers", (string)null);
                });

            modelBuilder.Entity("Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlayerCharacterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCharacterId");

                    b.ToTable("Spell");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int?>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("count");

                    b.Property<int?>("SelectedCharacter")
                        .HasColumnType("integer")
                        .HasColumnName("selected_character");

                    b.Property<string>("SelectedCharacterId")
                        .HasColumnType("text")
                        .HasColumnName("selected_character_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Campaign", b =>
                {
                    b.HasOne("User", "DungeonMaster")
                        .WithMany()
                        .HasForeignKey("DungeonMasterId");

                    b.Navigation("DungeonMaster");
                });

            modelBuilder.Entity("Gauge", b =>
                {
                    b.HasOne("PlayerCharacter", null)
                        .WithMany("Gauges")
                        .HasForeignKey("PlayerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IndividualRollResult", b =>
                {
                    b.HasOne("RollResult", null)
                        .WithMany("Rolls")
                        .HasForeignKey("RollResultId");
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.HasOne("PlayerCharacter", null)
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerCharacterId");
                });

            modelBuilder.Entity("PlayerCharacter", b =>
                {
                    b.HasOne("Campaign", "Campaign")
                        .WithMany("Players")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Roll", b =>
                {
                    b.HasOne("Item", null)
                        .WithMany("Rolls")
                        .HasForeignKey("ItemId");

                    b.HasOne("Spell", null)
                        .WithMany("Rolls")
                        .HasForeignKey("SpellId");
                });

            modelBuilder.Entity("RollResult", b =>
                {
                    b.HasOne("PlayerCharacter", null)
                        .WithMany("Rolls")
                        .HasForeignKey("PlayerCharacterId");
                });

            modelBuilder.Entity("Spell", b =>
                {
                    b.HasOne("PlayerCharacter", null)
                        .WithMany("Spells")
                        .HasForeignKey("PlayerCharacterId");
                });

            modelBuilder.Entity("Campaign", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.Navigation("Rolls");
                });

            modelBuilder.Entity("PlayerCharacter", b =>
                {
                    b.Navigation("Gauges");

                    b.Navigation("Inventory");

                    b.Navigation("Rolls");

                    b.Navigation("Spells");
                });

            modelBuilder.Entity("RollResult", b =>
                {
                    b.Navigation("Rolls");
                });

            modelBuilder.Entity("Spell", b =>
                {
                    b.Navigation("Rolls");
                });
#pragma warning restore 612, 618
        }
    }
}
